development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "56a3334db2e1f70b8d7e6f0890f9b1858968a25a72a1550a87089cafa1e5801e"
  signature_expiration: 3600 # one hour
